source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'
target 'easyVideo-iOS' do
inhibit_all_warnings!
pod 'CocoaLumberjack'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'HQHUtils', '1.0.9'
pod 'IQKeyboardManager'
pod 'GCDMulticastDelegate'
pod 'MBProgressHUD'
pod 'JGActionSheet'
pod 'WechatOpenSDK'
end
